spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/leadsdb
    username: leads
    password: leads
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: leads-api
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    listener:
      missing-topics-fatal: false
